#version: '2'
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    build: .
#    ports:
#      - "9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
version: '3.6'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka1:
    build: .
    ports:
      - "9092:9092"
    environment:
      #HOSTNAME_COMMAND: wget -t3 -T2 -qO-  http://xxx.xxx.xxx.xxx/latest/meta-data/local-ipv4
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      #KAFKA_LOG_RETENTION_HOURS: "2147483647"
    depends_on:
      - zookeeper
    volumes:
      - /home/mozat/data/kafka-logs/broker_1:/kafka/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  kafka2:
    build: .
    ports:
      - "9091:9092"
    environment:
      #HOSTNAME_COMMAND: wget -t3 -T2 -qO-  http://xxx.xxx.xxx.xxx/latest/meta-data/local-ipv4
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.1
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      #KAFKA_LOG_RETENTION_HOURS: "2147483647"
    depends_on:
      - zookeeper
    volumes:
      - /home/mozat/data/kafka-logs/broker_2:/kafka/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  kafka3:
    build: .
    ports:
     - "9090:9092"
    environment:
      #HOSTNAME_COMMAND: wget -t3 -T2 -qO-  http://xxx.xxx.xxx.xxx/latest/meta-data/local-ipv4
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.1
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      #KAFKA_LOG_RETENTION_HOURS: "2147483647"
    depends_on:
      - zookeeper
    volumes:
      - /home/mozat/data/kafka-logs/broker_3:/kafka/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always